const BestsellerData = [
    {
      id: 1,
      img: "https://m.media-amazon.com/images/I/71pzeBmtt-L._AC_UL480_FMwebp_QL65_.jpg",
      title: "Wireless Car charger",
      rating: 4,
      reviews: 4,
      newPrice: "240000",
      company: "Xiang",
      color: "black",
      category: "chair",
    },
    {
      id: 2,
      img: "https://m.media-amazon.com/images/I/81DxScjnZkL._AC_UY327_FMwebp_QL65_.jpg",
      title: "Vpro Bluetooth Speaker",
      rating: 3,
      reviews: 4,
      newPrice: "120000",
      company: "Sony",
      color: "black",
      category: "headset",
    },
    {
      id: 3,
      img: "https://m.media-amazon.com/images/I/71I03zlFz8L._AC_UY327_FMwebp_QL65_.jpg",
      title: "Sleep Headphone",
      rating: 5,
      reviews: 4,
      newPrice: "96000",
      company: "HP",
      color: "black",
      category: "laptop",
    },
    {
      id: 4,
      img: "https://m.media-amazon.com/images/I/71JkSYcii2L._AC_UY327_FMwebp_QL65_.jpg",
      title: "V4 Car Charger",
      rating: 5,
      reviews: 4,
      newPrice: "440000",
      company: "Xbox",
      color: "black",
      category: "games",
    },
    {
      id: 5,
      img: "https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_UY327_FMwebp_QL65_.jpg",
      title: "Apple Airpods Pro 2",
      rating: 5,
      reviews: 4,
      newPrice: "150000",
      company: "Xiang",
      color: "games",
      category: "black",
    },
    {
      id: 6,
      img: "https://m.media-amazon.com/images/I/7154009guGL._AC_UL480_FMwebp_QL65_.jpg",
      title: "Mkeke Iphone 16",
      rating: 5,
      reviews: 4,
      newPrice: "100000",
      company: "Xbox",
      color: "pink",
      category: "games",
    },
    {
      id: 7,
      img: "https://m.media-amazon.com/images/I/71LYHO3+wnL._AC_UL480_FMwebp_QL65_.jpg",
      title: "Zelt Microphone",
      rating: 4,
      reviews: 4,
      newPrice: "130000",
      company: "Xiang",
      color: "black",
      category: "others",
    },
    {
      id: 8,
      img: "https://m.media-amazon.com/images/I/71P0M7tKjYL._AC_UL480_FMwebp_QL65_.jpg",
      title: "Bomble Curved Monitor",
      rating: 5,
      reviews: 4,
      newPrice: "180000",
      company: "LG",
      color: "black",
      category: "others",
    },
    {
      id: 9,
      img: "https://m.media-amazon.com/images/I/61dXhRQiYTL._AC_UY327_FMwebp_QL65_.jpg",
      title: "VKGE Monitor",
      rating: 5,
      reviews: 4,
      newPrice: "640000",
      company: "Sony",
      color: "games",
      category: "white",
    },
    {
      id: 10,
      img: "https://m.media-amazon.com/images/I/5181ILcyQJL._AC_UY327_FMwebp_QL65_.jpg",
      title: "Bengoo Airbuds",
      rating: 5,
      reviews: 4,
      newPrice: "87000",
      company: "Acer",
      color: "blue",
      category: "headset",
    },
    {
      id: 11,
      img: "https://m.media-amazon.com/images/I/71I8VFCSIAL._AC_UL480_FMwebp_QL65_.jpg",
      title: "Autofill v4 Chair",
      rating: 5,
      reviews: 4,
      newPrice: "120000",
      company: "Xiang",
      color: "gray",
      category: "chair",
    },
    {
      id: 12,
      img: "https://m.media-amazon.com/images/I/61TLfc8EmNL._AC_UY327_FMwebp_QL65_.jpg",
      title: "Acer Aspire 5",
      rating: 5,
      reviews: 4,
      newPrice: "920000",
      company: "Acer",
      color: "nil",
      category: "laptop",
    },
    {
      id: 13,
      img: "https://m.media-amazon.com/images/I/61iBtxCUabL._AC_UY327_FMwebp_QL65_.jpg",
      title: "Apple Airbuds",
      rating: 5,
      reviews: 4,
      newPrice: "80000",
      company: "Sony",
      color: "white",
      category: "headset",
    },
    {
      id: 14,
      img: "https://m.media-amazon.com/images/I/61N9cUK98eL._AC_UY327_FMwebp_QL65_.jpg",
      title: "Xbox T320",
      rating: 5,
      reviews: 4,
      newPrice: "500000",
      company: "Sony",
      color: "white",
      category: "games",
    },
    {
      id: 15,
      img: "https://m.media-amazon.com/images/I/51FRJHB7XOL._AC_UY327_FMwebp_QL65_.jpg",
      title: "Racer BlackShark",
      rating: 5,
      reviews: 4,
      newPrice: "140000",
      company: "JBL",
      color: "gray",
      category: "headset",
    },
    {
      id: 16,
      img: "https://m.media-amazon.com/images/I/71+muMLin6L._AC_UY327_FMwebp_QL65_.jpg",
      title: "GT Laptop",
      rating: 5,
      reviews: 4,
      newPrice: "230000",
      company: "Xiang",
      color: "blue",
      category: "chair",
    },
    {
      id: 17,
      img: "https://m.media-amazon.com/images/I/81rslkP7ykL._AC_UY327_FMwebp_QL65_.jpg",
      title: "Jumper Monitor ",
      rating: 5,
      reviews: 4,
      newPrice: "110000",
      company: "JBL",
      color: "white",
      category: "headset",
    },
    {
      id: 18,
      img: "https://m.media-amazon.com/images/I/61B8Lq5NXmL._AC_UY327_FMwebp_QL65_.jpg",
      title: "Samsung Monitor P30",
      rating: 5,
      reviews: 4,
      newPrice: "430000",
      company: "LG",
      color: "black",
      category: "others",
    },
    {
      id: 19,
      img: "https://m.media-amazon.com/images/I/71geIOeuw-L._AC_UY327_FMwebp_QL65_.jpg",
      title: "C360 Headset",
      rating: 5,
      reviews: 4,
      newPrice: "70000",
      company: "JBL",
      color: "black",
      category: "others",
    },
    {
      id: 20,
      img: "https://m.media-amazon.com/images/I/71B+4V5YhnL._AC_UL480_FMwebp_QL65_.jpg",
      title: "Wireless charger",
      rating: 4.5,
      reviews: 4,
      newPrice: "20000",
      company: "Xiang",
      color: "black",
      category: "others",
    },
    {
      id: 21,
      img: "https://m.media-amazon.com/images/I/61mXcBwqDCL._AC_UL480_FMwebp_QL65_.jpg",
      title: "Cuktech Charger",
      rating: 2,
      reviews: 4,
      newPrice: "440000",
      company: "Samsung",
      color: "black",
      category: "others",
    },
  
    {
      id: 22,
      img: "https://m.media-amazon.com/images/I/61joErBxERL._AC_UY327_FMwebp_QL65_.jpg",
      title: "JBL Tune Flex",
      rating: 4,
      reviews: 4,
      newPrice: "150000",
      company: "JBL",
      color: "others",
      category: "black",
    },
    {
      id: 23,
      img: "https://m.media-amazon.com/images/I/71gR7cFe1UL._AC_UL480_FMwebp_QL65_.jpg",
      title: "Chair  A3 Massage",
      rating: 5,
      reviews: 4,
      newPrice: "250000",
      company: "Xiang",
      color: "red",
      category: "chairs",
    },
    {
      id: 24,
      img: "https://m.media-amazon.com/images/I/71ygD+0w49L._AC_UY327_FMwebp_QL65_.jpg",
      title: "Gaming Laptop",
      rating: 4,
      reviews: 4,
      newPrice: "900000",
      company: "Xiang",
      color: "nil",
      category: "laptop",
    },
    {
      id: 25,
      img: "https://m.media-amazon.com/images/I/614Jk1dIoGL._AC_UY327_FMwebp_QL65_.jpg",
      title: "Asus E410 Intel",
      rating: 4,
      reviews: 4,
      newPrice: "950000",
      company: "HP",
      color: "black",
      category: "laptop",
    },
    {
      id: 26,
      img: "https://m.media-amazon.com/images/I/81djh1gfUwL._AC_UY327_FMwebp_QL65_.jpg",
      title: "HB4 Speaker",
      rating: 5,
      reviews: 4,
      newPrice: "200000",
      company: "JBL",
      color: "black",
      category: "others",
    },
    {
      id: 27,
      img: "https://m.media-amazon.com/images/I/61z-rTknwVS._AC_UY327_FMwebp_QL65_.jpg",
      title: "RORSUS R10",
      rating: 4,
      reviews: 4,
      newPrice: "65000",
      company: "Sony",
      color: "red",
      category: "headset",
    },
    {
      id: 28,
      img: "https://m.media-amazon.com/images/I/6163yyOLZxL._AC_UL480_FMwebp_QL65_.jpg",
      title: "AAR49 Chair",
      rating: 3,
      reviews: 4,
      newPrice: "180000",
      company: "Xiang",
      color: "red",
      category: "chair",
    },
    {
      id: 29,
      img: "https://m.media-amazon.com/images/I/71bpmLxsMQL._AC_UY327_FMwebp_QL65_.jpg",
      title: "Sansui Monitor",
      rating: 3,
      reviews: 4,
      newPrice: "70000",
      company: "Xbox",
      color: "green",
      category: "games",
    },
    {
      id: 30,
      img: "https://m.media-amazon.com/images/I/61u0AqBTp3L._AC_UL480_FMwebp_QL65_.jpg",
      title: "Gaming Microphone",
      rating: 3,
      reviews: 4,
      newPrice: "150000",
      company: "Sony",
      color: "green",
      category: "headphone",
    },
  ];
  export default BestsellerData